#!/bin/bash
function getWavaHome {
    SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    echo "$(dirname "$DIR")"
}
export DEFAULT_CPU_AFINITY=`lscpu | awk -F ":" '$1 ~ /list/{ print $2; }' | sed 's/^ *//;s/ *$//'`
export DEFAULT_CAPACITY=$((`awk '/MemTotal/ {print $2}' /proc/meminfo`*1000*3/4))
export DEFAULT_SWAP=$((`awk '/SwapTotal/ {print $2}' /proc/meminfo`*1000))
export WAVA_HOME=$(getWavaHome)

java -version >/dev/null 2>&1 || { echo >&2 "Java is not installed. Aborting."; exit 1; }
if [ -t 0 ]; then
    export STDIN_TTY=true;
fi
if [ "$1" == "-s" ]; then
    MAX_HEAP=512M
else
    MAX_HEAP=10M
fi

java -Xmx$MAX_HEAP -Djava.util.logging.config.file=$WAVA_HOME/cfg/logging.properties -jar $WAVA_HOME/bin/wava-core-${project.version}.jar "$@" < /dev/stdin 1>&1 2>&2