#!/bin/bash
export DEFAULT_CPU_AFINITY=`lscpu | awk -F ":" '$1 ~ /list/{ print $2; }' | sed 's/^ *//;s/ *$//'`
if [ -z "$JAVA_HOME" ]; then 
    echo "JAVA_HOME environment variable not set"; 
    exit 1;
fi
if [ "$1" == "-s" ]; then
    MAX_HEAP=512M
else
    MAX_HEAP=10M
fi
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
export WAVA_HOME="$(dirname "$DIR")"
$JAVA_HOME/bin/java -Xmx$MAX_HEAP -jar $WAVA_HOME/bin/wava-core-${project.version}.jar "$@" < /dev/stdin 1>&1 2>&2