#!/bin/bash
if [ -z "$WAVA_HOME" ]; then
    echo "WAVA_HOME environment variable not set";
    exit 1;
fi

export USER=`whoami`
export CURRENT_VERSION=`wava -v &>/dev/null`
export WAVA_VERSION=`wget --no-check-certificate -O - -o /dev/null https://repo1.maven.org/maven2/org/brutusin/wava-core/maven-meta$

if [ "$USER" != "root" ]; then
    echo "root user is required to run this script"
    exit 1
fi

if [ -n "${CURRENT_VERSION}" ]; then
    echo Found installed version $CURRENT_VERSION
fi

if [ "$CURRENT_VERSION" == "$WAVA_VERSION" ]; then
    echo "Current version ($CURRENT_VERSION) is the latest"
    exit 1
fi

echo "Downloading latest version ($WAVA_VERSION)..."
wget --no-check-certificate -O /tmp/wava-latest-dist.zip "https://repository.sonatype.org/service/local/artifact/maven/content?r=ce$
if [ $? != 0 ]; then
    echo "Error downloading distribution file: https://repository.sonatype.org/service/local/artifact/maven/content?r=central-proxy$
    exit 1
fi

echo "Decompressing dist file..."
unzip -o /tmp/wava-latest-dist.zip -d /tmp &> /dev/null

if [ -d $WAVA_HOME ]; then
    echo "Checking current configuration..."
    cmp --silent $WAVA_HOME/cfg/wava.json.default /tmp/wava-core-$WAVA_VERSION/cfg/wava.json.default && cp -f $WAVA_HOME/cfg/wava.j$
fi

echo "Setting file permissions..."
chmod -R 555 /tmp/wava-core-$WAVA_VERSION

echo "Installing..."
rm -rf /$WAVA_HOME/wava-back
rm -rf /temp/wava-back
if [ -d "$WAVA_HOME" ]; then
    echo "Saving previous version..."
    mv -f $WAVA_HOME /tmp/wava-back
fi
mkdir -p $WAVA_HOME
mv /tmp/wava-core-$WAVA_VERSION/* $WAVA_HOME
if [ -d "/tmp/wava-back" ]; then
    mv -f /tmp/wava-back $WAVA_HOME/wava-back
fi
rm -rf /usr/bin/wava
cp $WAVA_HOME/bin/wava-home-aware /usr/bin/wava

echo "Running..."
wava